### ISSUE TITLE
investigate alternative to cgocheck=2 fatal error, Go pointer stored into non-Go memory

### ISSUE THREAD

**Issue by pcting** [godot-go/godot-go#12]
**Describe the bug**
When running with `cgocheck=2`, go reports the fatal error below. Investigate if there's a different solution to this.

```
write of Go pointer 0xc0003262b8 to non-Go memory 0x7c2bc60
fatal error: Go pointer stored into non-Go memory

runtime stack:
runtime.throw(0x7fa36b043a6f, 0x24)
        runtime/panic.go:1116 +0x74 fp=0x7ffe07f03848 sp=0x7ffe07f03818 pc=0x7fa36a48f5d4
runtime.cgoCheckWriteBarrier.func1()
        runtime/cgocheck.go:55 +0xaf fp=0x7ffe07f03878 sp=0x7ffe07f03848 pc=0x7fa36a4b9b6f
runtime.systemstack(0x7ffe07f03880)
        runtime/asm_amd64.s:370 +0x63 fp=0x7ffe07f03880 sp=0x7ffe07f03878 pc=0x7fa36a4c2ee3
runtime.mstart()
        runtime/proc.go:1116 fp=0x7ffe07f03888 sp=0x7ffe07f03880 pc=0x7fa36a494860

goroutine 17 [running, locked to thread]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xc0002cafc8 sp=0xc0002cafc0 pc=0x7fa36a4c2e60
runtime.cgoCheckWriteBarrier(0x7c2bc60, 0xc0003262b8)
        runtime/cgocheck.go:53 +0xd5 fp=0xc0002cb000 sp=0xc0002cafc8 pc=0x7fa36a45e355
runtime.wbBufFlush(0x7c2bc60, 0xc0003262b8)
        runtime/mwbbuf.go:196 +0x89 fp=0xc0002cb030 sp=0xc0002cb000 pc=0x7fa36a48a289
runtime.gcWriteBarrier(0x7fa36b2655c0, 0xc0003262b8, 0x2, 0x2, 0x7c2bc60, 0x36, 0xc0002cb108, 0x2, 0x2, 0x7c479f0, ...)
        runtime/asm_amd64.s:1461 +0xb1 fp=0xc0002cb0b8 sp=0xc0002cb030 pc=0x7fa36a4c4cf1
github.com/godot-go/godot-go/pkg/gdnative.ClassDBImpl.IsClassEnabled(0x68f0540, 0x5c049b39, 0x55104dc76695721d, 0x7c2ce00, 0x7fa36b2f7000)
        github.com/godot-go/godot-go/pkg/gdnative/classes.gen.go:401732 +0x1a5 fp=0xc0002cb150 sp=0xc0002cb0b8 pc=0x7fa36a937585
github.com/godot-go/godot-go/pkg/gdnative.(*ClassDBImpl).IsClassEnabled(0x7c479f0, 0x7c2ce00, 0x7c2ce00)
        <autogenerated>:1 +0x5a fp=0xc0002cb188 sp=0xc0002cb150 pc=0x7fa36ad2705a
github.com/godot-go/godot-go/test/pkg/gdnativetest.glob..func5.1()
        github.com/godot-go/godot-go/test/pkg/gdnativetest/tagdb_spec.go:19 +0x6b fp=0xc0002cb1e8 sp=0xc0002cb188 pc=0x7fa36afe874b
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000139560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:113 +0xa5 fp=0xc0002cb248 sp=0xc0002cb1e8 pc=0x7fa36afa8325
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000139560, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:64 +0xd7 fp=0xc0002cb3e8 sp=0xc0002cb248 pc=0x7fa36afa7f37
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc00012b760, 0x7fa36b309d60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/it_node.go:26 +0x67 fp=0xc0002cb508 sp=0xc0002cb3e8 pc=0x7fa36afa7347
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0002e21e0, 0x0, 0x7fa36b309d60, 0xc000144980)
        github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:215 +0x691 fp=0xc0002cb7f8 sp=0xc0002cb508 pc=0x7fa36afae4b1
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0002e21e0, 0x7fa36b309d60, 0xc000144980)
        github.com/onsi/ginkgo@v1.12.0/internal/spec/spec.go:138 +0xf5 fp=0xc0002cb848 sp=0xc0002cb7f8 pc=0x7fa36afadbf5
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000229b80, 0xc0002e21e0, 0x2)
        github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:200 +0x11c fp=0xc0002cb8a0 sp=0xc0002cb848 pc=0x7fa36afb3cdc
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000229b80, 0x1)
        github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:170 +0x127 fp=0xc0002cb928 sp=0xc0002cb8a0 pc=0x7fa36afb37e7
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000229b80, 0xc00027e7f8)
        github.com/onsi/ginkgo@v1.12.0/internal/specrunner/spec_runner.go:66 +0x119 fp=0xc0002cb968 sp=0xc0002cb928 pc=0x7fa36afb2fd9
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00013e230, 0x7fa368387040, 0xc0002b0360, 0x7fa36b03cb13, 0x1c, 0xc0002e12b0, 0x1, 0x1, 0x7fa36b328580, 0xc000144980, ...)
        github.com/onsi/ginkgo@v1.12.0/internal/suite/suite.go:62 +0x426 fp=0xc0002cbb28 sp=0xc0002cb968 pc=0x7fa36afb56a6
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x7fa368386fd8, 0xc0002b0360, 0x7fa36b03cb13, 0x1c, 0xc0002cbc90, 0x1, 0x1, 0x7fa36a464a67)
        github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:226 +0x238 fp=0xc0002cbc40 sp=0xc0002cbb28 pc=0x7fa36afb8858
github.com/onsi/ginkgo.RunSpecs(0x7fa368386fd8, 0xc0002b0360, 0x7fa36b03cb13, 0x1c, 0xc0002b0360)
        github.com/onsi/ginkgo@v1.12.0/ginkgo_dsl.go:207 +0x16a fp=0xc0002cbcb0 sp=0xc0002cbc40 pc=0x7fa36afb84aa
github.com/godot-go/godot-go/test/pkg/gdnativetest.runTests()
        github.com/godot-go/godot-go/test/pkg/gdnativetest/testsuite.go:49 +0x1a6 fp=0xc0002cbd08 sp=0xc0002cbcb0 pc=0x7fa36afe3846
github.com/godot-go/godot-go/test/pkg/gdnativetest.initNativescript()
        github.com/godot-go/godot-go/test/pkg/gdnativetest/testsuite.go:26 +0x8c fp=0xc0002cbd50 sp=0xc0002cbd08 pc=0x7fa36afe364c
github.com/godot-go/godot-go/pkg/gdnative.GodotNativescriptInit(0x7ffe07f039b0)
        github.com/godot-go/godot-go/pkg/gdnative/godot_exports.go:187 +0x2bd fp=0xc0002cbe50 sp=0xc0002cbd50 pc=0x7fa36a95531d
github.com/godot-go/godot-go/test/pkg/export.godot_nativescript_init(0x7ffe07f039b0)
        github.com/godot-go/godot-go/test/pkg/export/export.go:22 +0x2d fp=0xc0002cbe78 sp=0xc0002cbe50 pc=0x7fa36afffd0d
github.com/godot-go/godot-go/test/pkg/export._cgoexpwrap_ce579b02f98a_godot_nativescript_init(0x7ffe07f039b0)
        _cgo_gotypes.go:71 +0x2d fp=0xc0002cbe90 sp=0xc0002cbe78 pc=0x7fa36afffc8d
runtime.call32(0x0, 0x7ffe07f038d0, 0x7ffe07f03960, 0x8)
        runtime/asm_amd64.s:540 +0x40 fp=0xc0002cbec0 sp=0xc0002cbe90 pc=0x7fa36a4c3200
runtime.cgocallbackg1(0x0)
        runtime/cgocall.go:332 +0x1a5 fp=0xc0002cbf58 sp=0xc0002cbec0 pc=0x7fa36a45d245
runtime.cgocallbackg(0x0)
        runtime/cgocall.go:207 +0xc7 fp=0xc0002cbfc0 sp=0xc0002cbf58 pc=0x7fa36a45cfe7
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
        runtime/asm_amd64.s:794 +0x9a fp=0xc0002cbfe0 sp=0xc0002cbfc0 pc=0x7fa36a4c497a
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc0002cbfe8 sp=0xc0002cbfe0 pc=0x7fa36a4c4c21
```

**Comment by pcting** [comment]
closing this out. [go 1.21](https://tip.golang.org/doc/go1.21) will be releasing with the ability to pin go memory from being moved or gc'd. this will allow passing in go pointers that are pinned.
